name: coffee_venture_app
description: "Flutter application for Coffee Venture"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc_test: ^10.0.0
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  dartz: ^0.10.1
  design_system:
    path: ./packages/design_system
  cached_network_image: ^3.4.1
  flutter_modular: ^6.4.1
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  sqflite_common_ffi: any

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
